name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 
    - name: Install npm dependencies
      run: npm install

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Build your web application
      run: npm run build

    - name: Deploy to Firebase Hosting
      run: |
        # Determine the Firebase Hosting Channel based on the branch name 
        if ["${{github.ref}}" ="refs/header/main"]; then CHANNEL="refs/header/main"
        elif ["${{github.ref}}" ="refs/header/dev"]; then CHANNEL="refs/header/dev"
        elif ["${{github.ref}}" ="refs/header/staging"]; then CHANNEL="refs/header/staging"
        else
        # If the branch is not master, dev, or staging, exit without deploying echo "Branch not set up for deployment."
        exit 0
        fi

        # Deploy your application to the specified Hosting Channel 
        firebase hosting:channel:deploy "$CHANNEL" --token "FIREBASE_TOKEN"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
